---
- hosts: all

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    # OpenJDK
    - { role: "azavea.java", java_version: "7u75*" }
    # Oracle Java
    #- { role: "azavea.java", java_version: "7u76*", java_flavor: "oracle", java_oracle_accept_license_agreement: True }
